version = 0.1
[prod.deploy.parameters]
stack_name = "aws-microservice-data-visualiser"
resolve_s3 = true
s3_prefix = "aws-microservice-data-visualiser"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
