AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  data-visualiser

  Sample SAM Template for data-visualiser
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DestinationBucketName:
    Type: String

Resources:
  UpdateS3StaticWebsiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 512
      Architectures:
        - x86_64
      Environment:
        Variables:
          DestinationBucketName: !Ref DestinationBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
        - DynamoDBCrudPolicy:
            TableName: newweatherdata
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.ts

  UpdateS3StaticWebsiteFunctionSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: 'UpdateS3StaticWebsiteFunctionSchedule'
      ScheduleExpression: 'rate(1 day)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt UpdateS3StaticWebsiteFunction.Arn
        RoleArn: !GetAtt UpdateS3StaticWebsiteFunctionScheduleRole.Arn

  UpdateS3StaticWebsiteFunctionScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: UpdateS3StaticWebsiteFunctionScheduleRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt UpdateS3StaticWebsiteFunction.Arn

Outputs:
  UpdateS3StaticWebsiteFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UpdateS3StaticWebsiteFunction.Arn
  UpdateS3StaticWebsiteFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UpdateS3StaticWebsiteFunctionRole.Arn
